import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import '../../../core/constants/app_constants.dart';
import '../models/compression_request.dart';
import '../models/compression_result.dart';
import 'flutter_image_compress_adapter.dart';
import 'image_compressor_interface.dart';

class CompressionService {
  final ImageCompressorInterface _compressor;

  CompressionService({ImageCompressorInterface? compressor})
      : _compressor = compressor ?? const FlutterImageCompressAdapter();

  /// Compresses the image to fit under targetBytes while maximizing visual quality.
  Future<CompressionResult> compressToTarget(
    CompressionRequest request, {
    void Function(double progress, String status)? onProgress,
  }) async {
    final inputFile = File(request.inputPath);
    if (!await inputFile.exists()) {
      throw FileSystemException('Input file not found', request.inputPath);
    }

    final originalBytes = await inputFile.length();
    final fileBytes = await inputFile.readAsBytes();

    // Decode original dimensions
    final codec = await ui.instantiateImageCodec(fileBytes);
    final frame = await codec.getNextFrame();
    final origWidth = frame.image.width;
    final origHeight = frame.image.height;
    frame.image.dispose();

    onProgress?.call(0.1, 'Analyzing image...');

    // If already under target and preserveResolution requested,
    // or very close without needing compression
    if (originalBytes <= request.targetBytes && request.preserveResolution) {
      final tempDir = await getTemporaryDirectory();
      final tempOutPath = p.join(
        tempDir.path,
        'sizefit_orig_${DateTime.now().millisecondsSinceEpoch}.jpg',
      );
      await inputFile.copy(tempOutPath);

      return CompressionResult(
        originalBytes: originalBytes,
        resultBytes: originalBytes,
        originalWidth: origWidth,
        originalHeight: origHeight,
        resultWidth: origWidth,
        resultHeight: origHeight,
        quality: 100,
        scale: 1.0,
        outputPath: tempOutPath,
        resultBytesData: fileBytes,
        isQualityCompromised: false,
      );
    }

    final scales = request.preserveResolution
        ? [1.0]
        : AppConstants.scaleLevels;

    Uint8List? bestBytes;
    int bestQuality = 0;
    double bestScale = 1.0;
    int bestWidth = origWidth;
    int bestHeight = origHeight;
    bool isQualityCompromised = false;

    // Track smallest generated bytes in case extreme limit is required
    Uint8List? fallbackBytes;
    int fallbackQuality = AppConstants.minQuality;
    double fallbackScale = 1.0;
    int fallbackWidth = origWidth;
    int fallbackHeight = origHeight;

    int totalStepsEstimate = scales.length * AppConstants.maxBinarySearchSteps;
    int currentStep = 0;

    for (final scale in scales) {
      final currentW = (origWidth * scale).round();
      final currentH = (origHeight * scale).round();
      final longEdge = math.max(currentW, currentH);

      // Guard: do not reduce long edge below 480px unless no valid candidate exists
      if (longEdge < AppConstants.minLongEdgePx && bestBytes != null) {
        break;
      }
      if (longEdge < AppConstants.minLongEdgePx) {
        isQualityCompromised = true;
      }

      int lowQ = AppConstants.minQuality;
      int highQ = AppConstants.maxQuality;
      Uint8List? scaleBestBytes;
      int scaleBestQuality = 0;

      for (int iter = 0; iter < AppConstants.maxBinarySearchSteps; iter++) {
        if (lowQ > highQ) break;
        currentStep++;
        final progressRatio = (currentStep / totalStepsEstimate).clamp(0.1, 0.9);
        onProgress?.call(
          progressRatio,
          'Optimizing quality (${(scale * 100).toInt()}% resolution)...',
        );

        final midQ = (lowQ + highQ) ~/ 2;

        try {
          final compressed = await _compressor.compressWithFile(
            path: request.inputPath,
            minWidth: currentW,
            minHeight: currentH,
            quality: midQ,
            format: request.outputFormat,
            autoCorrectionAngle: true,
            keepExif: !request.removeLocationMetadata,
          );

          final compressedSize = compressed.lengthInBytes;

          // Track absolute minimum fallback
          if (fallbackBytes == null ||
              compressedSize < fallbackBytes.lengthInBytes) {
            fallbackBytes = compressed;
            fallbackQuality = midQ;
            fallbackScale = scale;
            fallbackWidth = currentW;
            fallbackHeight = currentH;
          }

          if (compressedSize <= request.targetBytes) {
            // Target satisfied! Save as candidate and try higher quality
            scaleBestBytes = compressed;
            scaleBestQuality = midQ;
            lowQ = midQ + 1;

            // Early exit if in sweet spot (-0% to -8%) and high quality
            if (compressedSize >= request.targetBytes * 0.92 && midQ >= 70) {
              break;
            }
          } else {
            // Exceeded target limit, lower the quality
            highQ = midQ - 1;
          }
        } catch (e) {
          debugPrint('Error in compression step: $e');
          highQ = midQ - 1;
        }
      }

      if (scaleBestBytes != null) {
        bestBytes = scaleBestBytes;
        bestQuality = scaleBestQuality;
        bestScale = scale;
        bestWidth = currentW;
        bestHeight = currentH;
        // Found the best quality candidate at this resolution; no need to downscale further!
        break;
      }
    }

    // If still no candidate met the target, use the smallest available fallback
    final finalBytes = bestBytes ?? fallbackBytes ?? fileBytes;
    final finalQuality = bestBytes != null ? bestQuality : fallbackQuality;
    final finalScale = bestBytes != null ? bestScale : fallbackScale;
    final finalWidth = bestBytes != null ? bestWidth : fallbackWidth;
    final finalHeight = bestBytes != null ? bestHeight : fallbackHeight;
    final finalCompromised =
        isQualityCompromised || (finalBytes.lengthInBytes > request.targetBytes);

    onProgress?.call(0.95, 'Finalizing image...');

    // Save final bytes to temporary output file
    final tempDir = await getTemporaryDirectory();
    final outExt = request.outputFormat.toLowerCase() == 'png' ? 'png' : 'jpg';
    final tempOutputPath = p.join(
      tempDir.path,
      'sizefit_${DateTime.now().millisecondsSinceEpoch}_fit.$outExt',
    );
    final outFile = File(tempOutputPath);
    await outFile.writeAsBytes(finalBytes, flush: true);

    onProgress?.call(1.0, 'Done');

    return CompressionResult(
      originalBytes: originalBytes,
      resultBytes: finalBytes.lengthInBytes,
      originalWidth: origWidth,
      originalHeight: origHeight,
      resultWidth: finalWidth,
      resultHeight: finalHeight,
      quality: finalQuality,
      scale: finalScale,
      outputPath: tempOutputPath,
      resultBytesData: finalBytes,
      isQualityCompromised: finalCompromised,
    );
  }
}
